name: neechathon
description: Neechathon
version: 0.0.1
environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  angular: ^5.3.1
  angular_forms: ^2.1.2
  angular_router: ^2.0.0-alpha+22
  http: ^0.11.3
  stream_transform: ^0.0.19


dev_dependencies:
  angular_test: ^2.2.0
  build_runner: ^1.6.3
  build_test: ^0.10.2
  build_web_compilers: ^1.0.0
  test: ^1.0.0
